#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NamedColor {
    Aliceblue,
    Antiquewhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    Black,
    Blanchedalmond,
    Blue,
    Blueviolet,
    Brown,
    Burlywood,
    Cadetblue,
    Chartreuse,
    Chocolate,
    Coral,
    Cornflowerblue,
    Cornsilk,
    Crimson,
    Cyan,
    Darkblue,
    Darkcyan,
    Darkgoldenrod,
    Darkgray,
    Darkgreen,
    Darkgrey,
    Darkkhaki,
    Darkmagenta,
    Darkolivegreen,
    Darkorange,
    Darkorchid,
    Darkred,
    Darksalmon,
    Darkseagreen,
    Darkslateblue,
    Darkslategray,
    Darkslategrey,
    Darkturquoise,
    Darkviolet,
    Deeppink,
    Deepskyblue,
    Dimgray,
    Dimgrey,
    Dodgerblue,
    Firebrick,
    Floralwhite,
    Forestgreen,
    Fuchsia,
    Gainsboro,
    Ghostwhite,
    Gold,
    Goldenrod,
    Gray,
    Green,
    Greenyellow,
    Grey,
    Honeydew,
    Hotpink,
    Indianred,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    Lavenderblush,
    Lawngreen,
    Lemonchiffon,
    Lightblue,
    Lightcoral,
    Lightcyan,
    Lightgoldenrodyellow,
    Lightgray,
    Lightgreen,
    Lightgrey,
    Lightpink,
    Lightsalmon,
    Lightseagreen,
    Lightskyblue,
    Lightslategray,
    Lightslategrey,
    Lightsteelblue,
    Lightyellow,
    Lime,
    Limegreen,
    Linen,
    Magenta,
    Maroon,
    Mediumaquamarine,
    Mediumblue,
    Mediumorchid,
    Mediumpurple,
    Mediumseagreen,
    Mediumslateblue,
    Mediumspringgreen,
    Mediumturquoise,
    Mediumvioletred,
    Midnightblue,
    Mintcream,
    Mistyrose,
    Moccasin,
    Navajowhite,
    Navy,
    Oldlace,
    Olive,
    Olivedrab,
    Orange,
    Orangered,
    Orchid,
    Palegoldenrod,
    Palegreen,
    Paleturquoise,
    Palevioletred,
    Papayawhip,
    Peachpuff,
    Peru,
    Pink,
    Plum,
    Powderblue,
    Purple,
    Rebeccapurple,
    Red,
    Rosybrown,
    Royalblue,
    Saddlebrown,
    Salmon,
    Sandybrown,
    Seagreen,
    Seashell,
    Sienna,
    Silver,
    Skyblue,
    Slateblue,
    Slategray,
    Slategrey,
    Snow,
    Springgreen,
    Steelblue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Turquoise,
    Violet,
    Wheat,
    White,
    Whitesmoke,
    Yellow,
    Yellowgreen,
    Transparent,
    Currentcolor
}

impl NamedColor {
    pub fn from_name(name: &str) -> Option<Self> {
        match name.to_lowercase().as_str() {
            "aliceblue" => Some(NamedColor::Aliceblue),
            "antiquewhite" => Some(NamedColor::Antiquewhite),
            "aqua" => Some(NamedColor::Aqua),
            "aquamarine" => Some(NamedColor::Aquamarine),
            "azure" => Some(NamedColor::Azure),
            "beige" => Some(NamedColor::Beige),
            "bisque" => Some(NamedColor::Bisque),
            "black" => Some(NamedColor::Black),
            "blanchedalmond" => Some(NamedColor::Blanchedalmond),
            "blue" => Some(NamedColor::Blue),
            "blueviolet" => Some(NamedColor::Blueviolet),
            "brown" => Some(NamedColor::Brown),
            "burlywood" => Some(NamedColor::Burlywood),
            "cadetblue" => Some(NamedColor::Cadetblue),
            "chartreuse" => Some(NamedColor::Chartreuse),
            "chocolate" => Some(NamedColor::Chocolate),
            "coral" => Some(NamedColor::Coral),
            "cornflowerblue" => Some(NamedColor::Cornflowerblue),
            "cornsilk" => Some(NamedColor::Cornsilk),
            "crimson" => Some(NamedColor::Crimson),
            "cyan" => Some(NamedColor::Cyan),
            "darkblue" => Some(NamedColor::Darkblue),
            "darkcyan" => Some(NamedColor::Darkcyan),
            "darkgoldenrod" => Some(NamedColor::Darkgoldenrod),
            "darkgray" => Some(NamedColor::Darkgray),
            "darkgreen" => Some(NamedColor::Darkgreen),
            "darkgrey" => Some(NamedColor::Darkgrey),
            "darkkhaki" => Some(NamedColor::Darkkhaki),
            "darkmagenta" => Some(NamedColor::Darkmagenta),
            "darkolivegreen" => Some(NamedColor::Darkolivegreen),
            "darkorange" => Some(NamedColor::Darkorange),
            "darkorchid" => Some(NamedColor::Darkorchid),
            "darkred" => Some(NamedColor::Darkred),
            "darksalmon" => Some(NamedColor::Darksalmon),
            "darkseagreen" => Some(NamedColor::Darkseagreen),
            "darkslateblue" => Some(NamedColor::Darkslateblue),
            "darkslategray" => Some(NamedColor::Darkslategray),
            "darkslategrey" => Some(NamedColor::Darkslategrey),
            "darkturquoise" => Some(NamedColor::Darkturquoise),
            "darkviolet" => Some(NamedColor::Darkviolet),
            "deeppink" => Some(NamedColor::Deeppink),
            "deepskyblue" => Some(NamedColor::Deepskyblue),
            "dimgray" => Some(NamedColor::Dimgray),
            "dimgrey" => Some(NamedColor::Dimgrey),
            "dodgerblue" => Some(NamedColor::Dodgerblue),
            "firebrick" => Some(NamedColor::Firebrick),
            "floralwhite" => Some(NamedColor::Floralwhite),
            "forestgreen" => Some(NamedColor::Forestgreen),
            "fuchsia" => Some(NamedColor::Fuchsia),
            "gainsboro" => Some(NamedColor::Gainsboro),
            "ghostwhite" => Some(NamedColor::Ghostwhite),
            "gold" => Some(NamedColor::Gold),
            "goldenrod" => Some(NamedColor::Goldenrod),
            "gray" => Some(NamedColor::Gray),
            "green" => Some(NamedColor::Green),
            "greenyellow" => Some(NamedColor::Greenyellow),
            "grey" => Some(NamedColor::Grey),
            "honeydew" => Some(NamedColor::Honeydew),
            "hotpink" => Some(NamedColor::Hotpink),
            "indianred" => Some(NamedColor::Indianred),
            "indigo" => Some(NamedColor::Indigo),
            "ivory" => Some(NamedColor::Ivory),
            "khaki" => Some(NamedColor::Khaki),
            "lavender" => Some(NamedColor::Lavender),
            "lavenderblush" => Some(NamedColor::Lavenderblush),
            "lawngreen" => Some(NamedColor::Lawngreen),
            "lemonchiffon" => Some(NamedColor::Lemonchiffon),
            "lightblue" => Some(NamedColor::Lightblue),
            "lightcoral" => Some(NamedColor::Lightcoral),
            "lightcyan" => Some(NamedColor::Lightcyan),
            "lightgoldenrodyellow" => Some(NamedColor::Lightgoldenrodyellow),
            "lightgray" => Some(NamedColor::Lightgray),
            "lightgreen" => Some(NamedColor::Lightgreen),
            "lightgrey" => Some(NamedColor::Lightgrey),
            "lightpink" => Some(NamedColor::Lightpink),
            "lightsalmon" => Some(NamedColor::Lightsalmon),
            "lightseagreen" => Some(NamedColor::Lightseagreen),
            "lightskyblue" => Some(NamedColor::Lightskyblue),
            "lightslategray" => Some(NamedColor::Lightslategray),
            "lightslategrey" => Some(NamedColor::Lightslategrey),
            "lightsteelblue" => Some(NamedColor::Lightsteelblue),
            "lightyellow" => Some(NamedColor::Lightyellow),
            "lime" => Some(NamedColor::Lime),
            "limegreen" => Some(NamedColor::Limegreen),
            "linen" => Some(NamedColor::Linen),
            "magenta" => Some(NamedColor::Magenta),
            "maroon" => Some(NamedColor::Maroon),
            "mediumaquamarine" => Some(NamedColor::Mediumaquamarine),
            "mediumblue" => Some(NamedColor::Mediumblue),
            "mediumorchid" => Some(NamedColor::Mediumorchid),
            "mediumpurple" => Some(NamedColor::Mediumpurple),
            "mediumseagreen" => Some(NamedColor::Mediumseagreen),
            "mediumslateblue" => Some(NamedColor::Mediumslateblue),
            "mediumspringgreen" => Some(NamedColor::Mediumspringgreen),
            "mediumturquoise" => Some(NamedColor::Mediumturquoise),
            "mediumvioletred" => Some(NamedColor::Mediumvioletred),
            "midnightblue" => Some(NamedColor::Midnightblue),
            "mintcream" => Some(NamedColor::Mintcream),
            "mistyrose" => Some(NamedColor::Mistyrose),
            "moccasin" => Some(NamedColor::Moccasin),
            "navajowhite" => Some(NamedColor::Navajowhite),
            "navy" => Some(NamedColor::Navy),
            "oldlace" => Some(NamedColor::Oldlace),
            "olive" => Some(NamedColor::Olive),
            "olivedrab" => Some(NamedColor::Olivedrab),
            "orange" => Some(NamedColor::Orange),
            "orangered" => Some(NamedColor::Orangered),
            "orchid" => Some(NamedColor::Orchid),
            "palegoldenrod" => Some(NamedColor::Palegoldenrod),
            "palegreen" => Some(NamedColor::Palegreen),
            "paleturquoise" => Some(NamedColor::Paleturquoise),
            "palevioletred" => Some(NamedColor::Palevioletred),
            "papayawhip" => Some(NamedColor::Papayawhip),
            "peachpuff" => Some(NamedColor::Peachpuff),
            "peru" => Some(NamedColor::Peru),
            "pink" => Some(NamedColor::Pink),
            "plum" => Some(NamedColor::Plum),
            "powderblue" => Some(NamedColor::Powderblue),
            "purple" => Some(NamedColor::Purple),
            "rebeccapurple" => Some(NamedColor::Rebeccapurple),
            "red" => Some(NamedColor::Red),
            "rosybrown" => Some(NamedColor::Rosybrown),
            "royalblue" => Some(NamedColor::Royalblue),
            "saddlebrown" => Some(NamedColor::Saddlebrown),
            "salmon" => Some(NamedColor::Salmon),
            "sandybrown" => Some(NamedColor::Sandybrown),
            "seagreen" => Some(NamedColor::Seagreen),
            "seashell" => Some(NamedColor::Seashell),
            "sienna" => Some(NamedColor::Sienna),
            "silver" => Some(NamedColor::Silver),
            "skyblue" => Some(NamedColor::Skyblue),
            "slateblue" => Some(NamedColor::Slateblue),
            "slategray" => Some(NamedColor::Slategray),
            "slategrey" => Some(NamedColor::Slategrey),
            "snow" => Some(NamedColor::Snow),
            "springgreen" => Some(NamedColor::Springgreen),
            "steelblue" => Some(NamedColor::Steelblue),
            "tan" => Some(NamedColor::Tan),
            "teal" => Some(NamedColor::Teal),
            "thistle" => Some(NamedColor::Thistle),
            "tomato" => Some(NamedColor::Tomato),
            "turquoise" => Some(NamedColor::Turquoise),
            "violet" => Some(NamedColor::Violet),
            "wheat" => Some(NamedColor::Wheat),
            "white" => Some(NamedColor::White),
            "whitesmoke" => Some(NamedColor::Whitesmoke),
            "yellow" => Some(NamedColor::Yellow),
            "yellowgreen" => Some(NamedColor::Yellowgreen),
            "transparent" => Some(NamedColor::Transparent),
            "currentcolor" => Some(NamedColor::Currentcolor),
            _ => return None,
        }
    }

    pub fn name(&self) -> &'static str {
        match self {
            NamedColor::Aliceblue => "aliceblue",
            NamedColor::Antiquewhite => "antiquewhite",
            NamedColor::Aqua => "aqua",
            NamedColor::Aquamarine => "aquamarine",
            NamedColor::Azure => "azure",
            NamedColor::Beige => "beige",
            NamedColor::Bisque => "bisque",
            NamedColor::Black => "black",
            NamedColor::Blanchedalmond => "blanchedalmond",
            NamedColor::Blue => "blue",
            NamedColor::Blueviolet => "blueviolet",
            NamedColor::Brown => "brown",
            NamedColor::Burlywood => "burlywood",
            NamedColor::Cadetblue => "cadetblue",
            NamedColor::Chartreuse => "chartreuse",
            NamedColor::Chocolate => "chocolate",
            NamedColor::Coral => "coral",
            NamedColor::Cornflowerblue => "cornflowerblue",
            NamedColor::Cornsilk => "cornsilk",
            NamedColor::Crimson => "crimson",
            NamedColor::Cyan => "cyan",
            NamedColor::Darkblue => "darkblue",
            NamedColor::Darkcyan => "darkcyan",
            NamedColor::Darkgoldenrod => "darkgoldenrod",
            NamedColor::Darkgray => "darkgray",
            NamedColor::Darkgreen => "darkgreen",
            NamedColor::Darkgrey => "darkgrey",
            NamedColor::Darkkhaki => "darkkhaki",
            NamedColor::Darkmagenta => "darkmagenta",
            NamedColor::Darkolivegreen => "darkolivegreen",
            NamedColor::Darkorange => "darkorange",
            NamedColor::Darkorchid => "darkorchid",
            NamedColor::Darkred => "darkred",
            NamedColor::Darksalmon => "darksalmon",
            NamedColor::Darkseagreen => "darkseagreen",
            NamedColor::Darkslateblue => "darkslateblue",
            NamedColor::Darkslategray => "darkslategray",
            NamedColor::Darkslategrey => "darkslategrey",
            NamedColor::Darkturquoise => "darkturquoise",
            NamedColor::Darkviolet => "darkviolet",
            NamedColor::Deeppink => "deeppink",
            NamedColor::Deepskyblue => "deepskyblue",
            NamedColor::Dimgray => "dimgray",
            NamedColor::Dimgrey => "dimgrey",
            NamedColor::Dodgerblue => "dodgerblue",
            NamedColor::Firebrick => "firebrick",
            NamedColor::Floralwhite => "floralwhite",
            NamedColor::Forestgreen => "forestgreen",
            NamedColor::Fuchsia => "fuchsia",
            NamedColor::Gainsboro => "gainsboro",
            NamedColor::Ghostwhite => "ghostwhite",
            NamedColor::Gold => "gold",
            NamedColor::Goldenrod => "goldenrod",
            NamedColor::Gray => "gray",
            NamedColor::Green => "green",
            NamedColor::Greenyellow => "greenyellow",
            NamedColor::Grey => "grey",
            NamedColor::Honeydew => "honeydew",
            NamedColor::Hotpink => "hotpink",
            NamedColor::Indianred => "indianred",
            NamedColor::Indigo => "indigo",
            NamedColor::Ivory => "ivory",
            NamedColor::Khaki => "khaki",
            NamedColor::Lavender => "lavender",
            NamedColor::Lavenderblush => "lavenderblush",
            NamedColor::Lawngreen => "lawngreen",
            NamedColor::Lemonchiffon => "lemonchiffon",
            NamedColor::Lightblue => "lightblue",
            NamedColor::Lightcoral => "lightcoral",
            NamedColor::Lightcyan => "lightcyan",
            NamedColor::Lightgoldenrodyellow => "lightgoldenrodyellow",
            NamedColor::Lightgray => "lightgray",
            NamedColor::Lightgreen => "lightgreen",
            NamedColor::Lightgrey => "lightgrey",
            NamedColor::Lightpink => "lightpink",
            NamedColor::Lightsalmon => "lightsalmon",
            NamedColor::Lightseagreen => "lightseagreen",
            NamedColor::Lightskyblue => "lightskyblue",
            NamedColor::Lightslategray => "lightslategray",
            NamedColor::Lightslategrey => "lightslategrey",
            NamedColor::Lightsteelblue => "lightsteelblue",
            NamedColor::Lightyellow => "lightyellow",
            NamedColor::Lime => "lime",
            NamedColor::Limegreen => "limegreen",
            NamedColor::Linen => "linen",
            NamedColor::Magenta => "magenta",
            NamedColor::Maroon => "maroon",
            NamedColor::Mediumaquamarine => "mediumaquamarine",
            NamedColor::Mediumblue => "mediumblue",
            NamedColor::Mediumorchid => "mediumorchid",
            NamedColor::Mediumpurple => "mediumpurple",
            NamedColor::Mediumseagreen => "mediumseagreen",
            NamedColor::Mediumslateblue => "mediumslateblue",
            NamedColor::Mediumspringgreen => "mediumspringgreen",
            NamedColor::Mediumturquoise => "mediumturquoise",
            NamedColor::Mediumvioletred => "mediumvioletred",
            NamedColor::Midnightblue => "midnightblue",
            NamedColor::Mintcream => "mintcream",
            NamedColor::Mistyrose => "mistyrose",
            NamedColor::Moccasin => "moccasin",
            NamedColor::Navajowhite => "navajowhite",
            NamedColor::Navy => "navy",
            NamedColor::Oldlace => "oldlace",
            NamedColor::Olive => "olive",
            NamedColor::Olivedrab => "olivedrab",
            NamedColor::Orange => "orange",
            NamedColor::Orangered => "orangered",
            NamedColor::Orchid => "orchid",
            NamedColor::Palegoldenrod => "palegoldenrod",
            NamedColor::Palegreen => "palegreen",
            NamedColor::Paleturquoise => "paleturquoise",
            NamedColor::Palevioletred => "palevioletred",
            NamedColor::Papayawhip => "papayawhip",
            NamedColor::Peachpuff => "peachpuff",
            NamedColor::Peru => "peru",
            NamedColor::Pink => "pink",
            NamedColor::Plum => "plum",
            NamedColor::Powderblue => "powderblue",
            NamedColor::Purple => "purple",
            NamedColor::Rebeccapurple => "rebeccapurple",
            NamedColor::Red => "red",
            NamedColor::Rosybrown => "rosybrown",
            NamedColor::Royalblue => "royalblue",
            NamedColor::Saddlebrown => "saddlebrown",
            NamedColor::Salmon => "salmon",
            NamedColor::Sandybrown => "sandybrown",
            NamedColor::Seagreen => "seagreen",
            NamedColor::Seashell => "seashell",
            NamedColor::Sienna => "sienna",
            NamedColor::Silver => "silver",
            NamedColor::Skyblue => "skyblue",
            NamedColor::Slateblue => "slateblue",
            NamedColor::Slategray => "slategray",
            NamedColor::Slategrey => "slategrey",
            NamedColor::Snow => "snow",
            NamedColor::Springgreen => "springgreen",
            NamedColor::Steelblue => "steelblue",
            NamedColor::Tan => "tan",
            NamedColor::Teal => "teal",
            NamedColor::Thistle => "thistle",
            NamedColor::Tomato => "tomato",
            NamedColor::Turquoise => "turquoise",
            NamedColor::Violet => "violet",
            NamedColor::Wheat => "wheat",
            NamedColor::White => "white",
            NamedColor::Whitesmoke => "whitesmoke",
            NamedColor::Yellow => "yellow",
            NamedColor::Yellowgreen => "yellowgreen",
            NamedColor::Transparent => "transparent",
            NamedColor::Currentcolor => "currentcolor",
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum CssColor {
    Named(NamedColor),
    Hex { r: u8, g: u8, b: u8, a: Option<u8> },
    Rgb { r: u8, g: u8, b: u8, a: Option<f64> },
    Hsl { h: f64, s: f64, l: f64, a: Option<f64> },
    Hwb { h: f64, w: f64, b: f64, a: Option<f64> },
}
