use std::collections::{HashMap, HashSet};

use crate::values::*;

#[derive(Debug, Clone, Default)]
pub struct Style {
  pub display: Option<Display>,
  pub position: Option<Position>,
  pub top: Option<CssLength>,
  pub right: Option<CssLength>,
  pub bottom: Option<CssLength>,
  pub left: Option<CssLength>,
  pub width: Option<CssLength>,
  pub height: Option<CssLength>,
  pub min_width: Option<CssLength>,
  pub min_height: Option<CssLength>,
  pub max_width: Option<CssLength>,
  pub max_height: Option<CssLength>,
  pub margin: Option<CssLength>,
  pub margin_top: Option<CssLength>,
  pub margin_right: Option<CssLength>,
  pub margin_bottom: Option<CssLength>,
  pub margin_left: Option<CssLength>,
  pub padding: Option<CssLength>,
  pub padding_top: Option<CssLength>,
  pub padding_right: Option<CssLength>,
  pub padding_bottom: Option<CssLength>,
  pub padding_left: Option<CssLength>,
  pub color: Option<CssColor>,
  pub accent_color: Option<CssColor>,
  pub background: Option<ArcStr>,
  pub background_color: Option<CssColor>,
  pub background_image: Option<CssImage>,
  pub background_size: Option<ArcStr>,
  pub background_position: Option<ArcStr>,
  pub background_repeat: Option<BackgroundRepeat>,
  pub background_clip: Option<BackgroundClip>,
  pub border: Option<ArcStr>,

  pub border_top_width: Option<CssLength>,
  pub border_right_width: Option<CssLength>,
  pub border_bottom_width: Option<CssLength>,
  pub border_left_width: Option<CssLength>,

  pub border_top_style: Option<BorderStyle>,
  pub border_right_style: Option<BorderStyle>,
  pub border_bottom_style: Option<BorderStyle>,
  pub border_left_style: Option<BorderStyle>,

  pub border_top_color: Option<CssColor>,
  pub border_right_color: Option<CssColor>,
  pub border_bottom_color: Option<CssColor>,
  pub border_left_color: Option<CssColor>,

  pub border_top_left_radius: Option<CssLength>,
  pub border_top_right_radius: Option<CssLength>,
  pub border_bottom_right_radius: Option<CssLength>,
  pub border_bottom_left_radius: Option<CssLength>,

  pub border_top_left_radius_v: Option<CssLength>,
  pub border_top_right_radius_v: Option<CssLength>,
  pub border_bottom_right_radius_v: Option<CssLength>,
  pub border_bottom_left_radius_v: Option<CssLength>,

  pub font_family: Option<ArcStr>,
  pub font_size: Option<CssLength>,
  pub font_weight: Option<FontWeight>,
  pub font_style: Option<FontStyle>,
  pub line_height: Option<CssLength>,
  pub letter_spacing: Option<CssLength>,
  pub text_align: Option<TextAlign>,
  pub text_decoration: Option<ArcStr>,
  pub text_transform: Option<TextTransform>,
  pub white_space: Option<WhiteSpace>,
  pub vertical_align: Option<VerticalAlign>,
  pub word_break: Option<WordBreak>,
  pub text_overflow: Option<TextOverflow>,
  pub overflow: Option<Overflow>,
  pub overflow_x: Option<Overflow>,
  pub overflow_y: Option<Overflow>,
  pub scrollbar_color: Option<ScrollbarColor>,
  pub scrollbar_width: Option<ScrollbarWidth>,
  pub resize: Option<Resize>,
  pub opacity: Option<f32>,
  pub visibility: Option<Visibility>,
  pub z_index: Option<i32>,

  pub svg_fill: Option<CssColor>,
  pub svg_fill_opacity: Option<f32>,
  pub svg_fill_rule: Option<ArcStr>,
  pub svg_stroke: Option<CssColor>,
  pub svg_stroke_width: Option<CssLength>,
  pub svg_stroke_opacity: Option<f32>,
  pub svg_stroke_linecap: Option<ArcStr>,
  pub svg_stroke_linejoin: Option<ArcStr>,
  pub svg_stroke_dasharray: Option<ArcStr>,
  pub svg_stroke_dashoffset: Option<CssLength>,

  pub flex_direction: Option<FlexDirection>,
  pub flex_wrap: Option<FlexWrap>,
  pub justify_content: Option<JustifyContent>,
  pub align_items: Option<AlignItems>,
  pub align_content: Option<AlignContent>,
  pub align_self: Option<AlignSelf>,
  pub order: Option<i32>,
  pub gap: Option<CssLength>,
  pub row_gap: Option<CssLength>,
  pub column_gap: Option<CssLength>,
  pub flex: Option<ArcStr>,
  pub flex_grow: Option<f32>,
  pub flex_shrink: Option<f32>,
  pub flex_basis: Option<CssLength>,

  pub grid_template_columns: Option<Vec<GridTrackSize>>,
  pub grid_template_rows: Option<Vec<GridTrackSize>>,
  pub grid_auto_columns: Option<GridTrackSize>,
  pub grid_auto_rows: Option<GridTrackSize>,
  pub grid_auto_flow: Option<GridAutoFlow>,
  pub grid_column_start: Option<GridLine>,
  pub grid_column_end: Option<GridLine>,
  pub grid_row_start: Option<GridLine>,
  pub grid_row_end: Option<GridLine>,
  pub grid_column: Option<ArcStr>,
  pub grid_row: Option<ArcStr>,
  pub justify_items: Option<JustifyItems>,
  pub justify_self: Option<JustifySelf>,

  pub transform: Option<ArcStr>,
  pub transform_origin: Option<ArcStr>,
  pub transition: Option<ArcStr>,
  pub animation: Option<ArcStr>,
  pub cursor: Option<Cursor>,
  pub pointer_events: Option<PointerEvents>,
  pub user_select: Option<UserSelect>,
  pub content: Option<CssContent>,
  pub list_style_type: Option<ListStyleType>,
  pub list_style_position: Option<ListStylePosition>,
  pub box_shadow: Option<ArcStr>,
  pub box_sizing: Option<BoxSizing>,

  pub deferred_longhands: HashMap<ArcStr, ArcStr>,
  pub custom_properties: HashMap<ArcStr, ArcStr>,
  pub var_properties: HashMap<ArcStr, ArcStr>,
  pub reset_properties: HashSet<ArcStr>,
  pub keyword_reset_properties: HashSet<ArcStr>,
}

#[derive(Debug, Clone, Default)]
pub struct LuiPopupStyle {
  pub width: Option<CssLength>,
  pub height: Option<CssLength>,
  pub background_color: Option<CssColor>,
  pub color: Option<CssColor>,
  pub border_top_width: Option<CssLength>,
  pub border_right_width: Option<CssLength>,
  pub border_bottom_width: Option<CssLength>,
  pub border_left_width: Option<CssLength>,
  pub border_top_style: Option<BorderStyle>,
  pub border_right_style: Option<BorderStyle>,
  pub border_bottom_style: Option<BorderStyle>,
  pub border_left_style: Option<BorderStyle>,
  pub border_top_color: Option<CssColor>,
  pub border_right_color: Option<CssColor>,
  pub border_bottom_color: Option<CssColor>,
  pub border_left_color: Option<CssColor>,
  pub border_radius: Option<CssLength>,
  pub font_size: Option<CssLength>,
  pub font_family: Option<ArcStr>,
  pub font_weight: Option<FontWeight>,
}

#[derive(Debug, Clone, Default)]
pub struct LuiColorPickerStyle {
  pub canvas_width: Option<CssLength>,
  pub canvas_height: Option<CssLength>,
  pub range_height: Option<CssLength>,
  pub range_border_radius: Option<CssLength>,
  pub thumb_width: Option<CssLength>,
  pub thumb_height: Option<CssLength>,
  pub thumb_color: Option<CssColor>,
  pub input_height: Option<CssLength>,
  pub input_background: Option<CssColor>,
  pub input_border_color: Option<CssColor>,
  pub input_border_width: Option<CssLength>,
  pub input_border_radius: Option<CssLength>,
  pub input_font_size: Option<CssLength>,
}

#[derive(Debug, Clone, Default)]
pub struct LuiCalendarStyle {
  pub padding: Option<CssLength>,
  pub gap: Option<CssLength>,
  pub cell_size: Option<CssLength>,
  pub cell_radius: Option<CssLength>,
  pub selected_bg: Option<CssColor>,
  pub selected_color: Option<CssColor>,
  pub today_color: Option<CssColor>,
  pub today_width: Option<CssLength>,
  pub dim: Option<CssColor>,
  pub nav_size: Option<CssLength>,
  pub header_font_size: Option<CssLength>,
  pub header_font_weight: Option<FontWeight>,
  pub weekday_font_size: Option<CssLength>,
  pub day_font_size: Option<CssLength>,
  pub time_width: Option<CssLength>,
  pub time_height: Option<CssLength>,
  pub time_background: Option<CssColor>,
  pub time_border_color: Option<CssColor>,
  pub time_border_width: Option<CssLength>,
  pub time_border_radius: Option<CssLength>,
  pub time_font_size: Option<CssLength>,
  pub reset_height: Option<CssLength>,
  pub reset_background: Option<CssColor>,
  pub reset_color: Option<CssColor>,
  pub reset_border_color: Option<CssColor>,
  pub reset_border_width: Option<CssLength>,
  pub reset_border_radius: Option<CssLength>,
  pub reset_font_size: Option<CssLength>,
}
