use super::meta;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PropertyId {
  // Display & positioning
  Display,
  Position,
  Top,
  Right,
  Bottom,
  Left,

  // Sizing
  Width,
  Height,
  MinWidth,
  MinHeight,
  MaxWidth,
  MaxHeight,

  // Margin (shorthand + longhands)
  Margin,
  MarginTop,
  MarginRight,
  MarginBottom,
  MarginLeft,

  // Padding (shorthand + longhands)
  Padding,
  PaddingTop,
  PaddingRight,
  PaddingBottom,
  PaddingLeft,

  // Color
  Color,
  AccentColor,

  // Background
  Background,
  BackgroundColor,
  BackgroundImage,
  BackgroundSize,
  BackgroundPosition,
  BackgroundRepeat,
  BackgroundClip,

  // Border (shorthand + longhands)
  Border,
  BorderTopWidth,
  BorderRightWidth,
  BorderBottomWidth,
  BorderLeftWidth,
  BorderTopStyle,
  BorderRightStyle,
  BorderBottomStyle,
  BorderLeftStyle,
  BorderTopColor,
  BorderRightColor,
  BorderBottomColor,
  BorderLeftColor,
  BorderRadius,
  BorderTopLeftRadius,
  BorderTopRightRadius,
  BorderBottomRightRadius,
  BorderBottomLeftRadius,

  // Typography
  FontFamily,
  FontSize,
  FontWeight,
  FontStyle,
  LineHeight,
  LetterSpacing,
  TextAlign,
  TextDecoration,
  TextTransform,
  WhiteSpace,
  WordBreak,
  VerticalAlign,
  TextOverflow,

  // Overflow
  Overflow,
  OverflowX,
  OverflowY,
  ScrollbarColor,
  ScrollbarWidth,
  Resize,

  // Visual
  Opacity,
  Visibility,
  ZIndex,

  // SVG
  Fill,
  FillOpacity,
  FillRule,
  Stroke,
  StrokeWidth,
  StrokeOpacity,
  StrokeLinecap,
  StrokeLinejoin,
  StrokeDasharray,
  StrokeDashoffset,

  // Flexbox
  FlexDirection,
  FlexWrap,
  JustifyContent,
  AlignItems,
  AlignContent,
  AlignSelf,
  Order,
  Gap,
  RowGap,
  ColumnGap,
  Flex,
  FlexGrow,
  FlexShrink,
  FlexBasis,

  // Grid
  GridTemplateColumns,
  GridTemplateRows,
  GridAutoColumns,
  GridAutoRows,
  GridAutoFlow,
  GridColumn,
  GridColumnStart,
  GridColumnEnd,
  GridRow,
  GridRowStart,
  GridRowEnd,
  JustifyItems,
  JustifySelf,

  // Transform & animation
  Transform,
  TransformOrigin,
  Transition,
  Animation,

  // Interaction
  Cursor,
  PointerEvents,
  UserSelect,

  // Content & list
  Content,
  ListStyleType,
  ListStylePosition,

  // Box
  BoxShadow,
  BoxSizing,

  // Custom property (--*)
  Custom,
}

impl PropertyId {
  pub fn from_name(name: &str) -> Option<Self> {
    if name.starts_with("--") {
      return Some(PropertyId::Custom);
    }
    match name {
      "display" => Some(Self::Display),
      "position" => Some(Self::Position),
      "top" => Some(Self::Top),
      "right" => Some(Self::Right),
      "bottom" => Some(Self::Bottom),
      "left" => Some(Self::Left),
      "width" => Some(Self::Width),
      "height" => Some(Self::Height),
      "min-width" => Some(Self::MinWidth),
      "min-height" => Some(Self::MinHeight),
      "max-width" => Some(Self::MaxWidth),
      "max-height" => Some(Self::MaxHeight),
      "margin" => Some(Self::Margin),
      "margin-top" => Some(Self::MarginTop),
      "margin-right" => Some(Self::MarginRight),
      "margin-bottom" => Some(Self::MarginBottom),
      "margin-left" => Some(Self::MarginLeft),
      "padding" => Some(Self::Padding),
      "padding-top" => Some(Self::PaddingTop),
      "padding-right" => Some(Self::PaddingRight),
      "padding-bottom" => Some(Self::PaddingBottom),
      "padding-left" => Some(Self::PaddingLeft),
      "color" => Some(Self::Color),
      "accent-color" => Some(Self::AccentColor),
      "background" => Some(Self::Background),
      "background-color" => Some(Self::BackgroundColor),
      "background-image" => Some(Self::BackgroundImage),
      "background-size" => Some(Self::BackgroundSize),
      "background-position" => Some(Self::BackgroundPosition),
      "background-repeat" => Some(Self::BackgroundRepeat),
      "background-clip" => Some(Self::BackgroundClip),
      "border" => Some(Self::Border),
      "border-top-width" => Some(Self::BorderTopWidth),
      "border-right-width" => Some(Self::BorderRightWidth),
      "border-bottom-width" => Some(Self::BorderBottomWidth),
      "border-left-width" => Some(Self::BorderLeftWidth),
      "border-top-style" => Some(Self::BorderTopStyle),
      "border-right-style" => Some(Self::BorderRightStyle),
      "border-bottom-style" => Some(Self::BorderBottomStyle),
      "border-left-style" => Some(Self::BorderLeftStyle),
      "border-top-color" => Some(Self::BorderTopColor),
      "border-right-color" => Some(Self::BorderRightColor),
      "border-bottom-color" => Some(Self::BorderBottomColor),
      "border-left-color" => Some(Self::BorderLeftColor),
      "border-radius" => Some(Self::BorderRadius),
      "border-top-left-radius" => Some(Self::BorderTopLeftRadius),
      "border-top-right-radius" => Some(Self::BorderTopRightRadius),
      "border-bottom-right-radius" => Some(Self::BorderBottomRightRadius),
      "border-bottom-left-radius" => Some(Self::BorderBottomLeftRadius),
      "font-family" => Some(Self::FontFamily),
      "font-size" => Some(Self::FontSize),
      "font-weight" => Some(Self::FontWeight),
      "font-style" => Some(Self::FontStyle),
      "line-height" => Some(Self::LineHeight),
      "letter-spacing" => Some(Self::LetterSpacing),
      "text-align" => Some(Self::TextAlign),
      "text-decoration" => Some(Self::TextDecoration),
      "text-transform" => Some(Self::TextTransform),
      "white-space" => Some(Self::WhiteSpace),
      "word-break" => Some(Self::WordBreak),
      "vertical-align" => Some(Self::VerticalAlign),
      "text-overflow" => Some(Self::TextOverflow),
      "overflow" => Some(Self::Overflow),
      "overflow-x" => Some(Self::OverflowX),
      "overflow-y" => Some(Self::OverflowY),
      "scrollbar-color" => Some(Self::ScrollbarColor),
      "scrollbar-width" => Some(Self::ScrollbarWidth),
      "resize" => Some(Self::Resize),
      "opacity" => Some(Self::Opacity),
      "visibility" => Some(Self::Visibility),
      "z-index" => Some(Self::ZIndex),
      "fill" => Some(Self::Fill),
      "fill-opacity" => Some(Self::FillOpacity),
      "fill-rule" => Some(Self::FillRule),
      "stroke" => Some(Self::Stroke),
      "stroke-width" => Some(Self::StrokeWidth),
      "stroke-opacity" => Some(Self::StrokeOpacity),
      "stroke-linecap" => Some(Self::StrokeLinecap),
      "stroke-linejoin" => Some(Self::StrokeLinejoin),
      "stroke-dasharray" => Some(Self::StrokeDasharray),
      "stroke-dashoffset" => Some(Self::StrokeDashoffset),
      "flex-direction" => Some(Self::FlexDirection),
      "flex-wrap" => Some(Self::FlexWrap),
      "justify-content" => Some(Self::JustifyContent),
      "align-items" => Some(Self::AlignItems),
      "align-content" => Some(Self::AlignContent),
      "align-self" => Some(Self::AlignSelf),
      "order" => Some(Self::Order),
      "gap" => Some(Self::Gap),
      "row-gap" => Some(Self::RowGap),
      "column-gap" => Some(Self::ColumnGap),
      "flex" => Some(Self::Flex),
      "flex-grow" => Some(Self::FlexGrow),
      "flex-shrink" => Some(Self::FlexShrink),
      "flex-basis" => Some(Self::FlexBasis),
      "grid-template-columns" => Some(Self::GridTemplateColumns),
      "grid-template-rows" => Some(Self::GridTemplateRows),
      "grid-auto-columns" => Some(Self::GridAutoColumns),
      "grid-auto-rows" => Some(Self::GridAutoRows),
      "grid-auto-flow" => Some(Self::GridAutoFlow),
      "grid-column" => Some(Self::GridColumn),
      "grid-column-start" => Some(Self::GridColumnStart),
      "grid-column-end" => Some(Self::GridColumnEnd),
      "grid-row" => Some(Self::GridRow),
      "grid-row-start" => Some(Self::GridRowStart),
      "grid-row-end" => Some(Self::GridRowEnd),
      "justify-items" => Some(Self::JustifyItems),
      "justify-self" => Some(Self::JustifySelf),
      "transform" => Some(Self::Transform),
      "transform-origin" => Some(Self::TransformOrigin),
      "transition" => Some(Self::Transition),
      "animation" => Some(Self::Animation),
      "cursor" => Some(Self::Cursor),
      "pointer-events" => Some(Self::PointerEvents),
      "user-select" => Some(Self::UserSelect),
      "content" => Some(Self::Content),
      "list-style-type" => Some(Self::ListStyleType),
      "list-style-position" => Some(Self::ListStylePosition),
      "box-shadow" => Some(Self::BoxShadow),
      "box-sizing" => Some(Self::BoxSizing),
      _ => None,
    }
  }

  pub fn as_css_name(&self) -> &'static str {
    match self {
      Self::Display => "display",
      Self::Position => "position",
      Self::Top => "top",
      Self::Right => "right",
      Self::Bottom => "bottom",
      Self::Left => "left",
      Self::Width => "width",
      Self::Height => "height",
      Self::MinWidth => "min-width",
      Self::MinHeight => "min-height",
      Self::MaxWidth => "max-width",
      Self::MaxHeight => "max-height",
      Self::Margin => "margin",
      Self::MarginTop => "margin-top",
      Self::MarginRight => "margin-right",
      Self::MarginBottom => "margin-bottom",
      Self::MarginLeft => "margin-left",
      Self::Padding => "padding",
      Self::PaddingTop => "padding-top",
      Self::PaddingRight => "padding-right",
      Self::PaddingBottom => "padding-bottom",
      Self::PaddingLeft => "padding-left",
      Self::Color => "color",
      Self::AccentColor => "accent-color",
      Self::Background => "background",
      Self::BackgroundColor => "background-color",
      Self::BackgroundImage => "background-image",
      Self::BackgroundSize => "background-size",
      Self::BackgroundPosition => "background-position",
      Self::BackgroundRepeat => "background-repeat",
      Self::BackgroundClip => "background-clip",
      Self::Border => "border",
      Self::BorderTopWidth => "border-top-width",
      Self::BorderRightWidth => "border-right-width",
      Self::BorderBottomWidth => "border-bottom-width",
      Self::BorderLeftWidth => "border-left-width",
      Self::BorderTopStyle => "border-top-style",
      Self::BorderRightStyle => "border-right-style",
      Self::BorderBottomStyle => "border-bottom-style",
      Self::BorderLeftStyle => "border-left-style",
      Self::BorderTopColor => "border-top-color",
      Self::BorderRightColor => "border-right-color",
      Self::BorderBottomColor => "border-bottom-color",
      Self::BorderLeftColor => "border-left-color",
      Self::BorderRadius => "border-radius",
      Self::BorderTopLeftRadius => "border-top-left-radius",
      Self::BorderTopRightRadius => "border-top-right-radius",
      Self::BorderBottomRightRadius => "border-bottom-right-radius",
      Self::BorderBottomLeftRadius => "border-bottom-left-radius",
      Self::FontFamily => "font-family",
      Self::FontSize => "font-size",
      Self::FontWeight => "font-weight",
      Self::FontStyle => "font-style",
      Self::LineHeight => "line-height",
      Self::LetterSpacing => "letter-spacing",
      Self::TextAlign => "text-align",
      Self::TextDecoration => "text-decoration",
      Self::TextTransform => "text-transform",
      Self::WhiteSpace => "white-space",
      Self::WordBreak => "word-break",
      Self::VerticalAlign => "vertical-align",
      Self::TextOverflow => "text-overflow",
      Self::Overflow => "overflow",
      Self::OverflowX => "overflow-x",
      Self::OverflowY => "overflow-y",
      Self::ScrollbarColor => "scrollbar-color",
      Self::ScrollbarWidth => "scrollbar-width",
      Self::Resize => "resize",
      Self::Opacity => "opacity",
      Self::Visibility => "visibility",
      Self::ZIndex => "z-index",
      Self::Fill => "fill",
      Self::FillOpacity => "fill-opacity",
      Self::FillRule => "fill-rule",
      Self::Stroke => "stroke",
      Self::StrokeWidth => "stroke-width",
      Self::StrokeOpacity => "stroke-opacity",
      Self::StrokeLinecap => "stroke-linecap",
      Self::StrokeLinejoin => "stroke-linejoin",
      Self::StrokeDasharray => "stroke-dasharray",
      Self::StrokeDashoffset => "stroke-dashoffset",
      Self::FlexDirection => "flex-direction",
      Self::FlexWrap => "flex-wrap",
      Self::JustifyContent => "justify-content",
      Self::AlignItems => "align-items",
      Self::AlignContent => "align-content",
      Self::AlignSelf => "align-self",
      Self::Order => "order",
      Self::Gap => "gap",
      Self::RowGap => "row-gap",
      Self::ColumnGap => "column-gap",
      Self::Flex => "flex",
      Self::FlexGrow => "flex-grow",
      Self::FlexShrink => "flex-shrink",
      Self::FlexBasis => "flex-basis",
      Self::GridTemplateColumns => "grid-template-columns",
      Self::GridTemplateRows => "grid-template-rows",
      Self::GridAutoColumns => "grid-auto-columns",
      Self::GridAutoRows => "grid-auto-rows",
      Self::GridAutoFlow => "grid-auto-flow",
      Self::GridColumn => "grid-column",
      Self::GridColumnStart => "grid-column-start",
      Self::GridColumnEnd => "grid-column-end",
      Self::GridRow => "grid-row",
      Self::GridRowStart => "grid-row-start",
      Self::GridRowEnd => "grid-row-end",
      Self::JustifyItems => "justify-items",
      Self::JustifySelf => "justify-self",
      Self::Transform => "transform",
      Self::TransformOrigin => "transform-origin",
      Self::Transition => "transition",
      Self::Animation => "animation",
      Self::Cursor => "cursor",
      Self::PointerEvents => "pointer-events",
      Self::UserSelect => "user-select",
      Self::Content => "content",
      Self::ListStyleType => "list-style-type",
      Self::ListStylePosition => "list-style-position",
      Self::BoxShadow => "box-shadow",
      Self::BoxSizing => "box-sizing",
      Self::Custom => "--*",
    }
  }

  pub fn is_inherited(&self) -> bool {
    meta::is_inherited(self.as_css_name())
  }

  pub fn is_shorthand(&self) -> bool {
    meta::is_shorthand(self.as_css_name())
  }
}

impl std::fmt::Display for PropertyId {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.write_str(self.as_css_name())
  }
}
